__default__:
    job-name: "{rule}"
    partition: "c"
    qos: "c_short"
    time: "08:00:00"
    mem: "16G"
    output: "logs/{rule}/%j.{rule}.{wildcards}.out"
    error: "logs/{rule}/%j.{rule}.{wildcards}.err"

run_simulation:
    partition: "g"
    qos: "g_short"
    constraint: "g3"
    cpus-per-gpu: 1
    gres: "gpu:1"

create_maps:
    partition: "c"
    qos: "c_medium"
    time: "2-00:00:00"
    mem: "32G"
    cpus-per-task: 8