name: 'yeast_cen_intertwines'
logs_dir: 'logs'
simulation:
    script: 'scripts/run_simulation.py'
    out_dir: 'results/simulations'
    replicates: 2
    parameters_file: 'config/parameters.tsv'
    parameters:
        rep_e:
            - 10
        chain_length:
            - 500
        mt_len:
            - 3
            - 5
        int_n:
            - 0
            - 1
        int_r:
            - 1.0
        int_region:
            - 100
        gap_p:
            - 0
        fix_tel:
            - true
        timesteps:
            - 10000
analyses:
    create_maps:
        script: 'scripts/create_maps.py'
        out_dir: 'results/analyses/maps/raw'
        parameters:
            assembly: 'chains'
            bin_size: 10
            blocks: -200
    plot_maps:
        script: 'scripts/plot_maps.py'
        out_dir: 'results/analyses/maps/plots'