name: 'yeast_cen_intertwines'
logs_dir: 'logs'
simulation:
    script: 'scripts/test.py'
    out_dir: 'results/simulations'
    replicates: 5
    parameters:
        rep_e:
            - 10
        chain_length:
            - 2000
        mt_len:
            - 3
            - 30
        int_n:
            - 0
            - 10
        int_r:
            - 1.0
        int_region:
            - 100
        gap_p:
            - 0
            - 2
        fix_tel:
            - true
        timesteps:
            - 100000000
analyses:
    dir: 'results/analyses'
    create_maps:
        script: 'scripts/sims_to_map.py'
        out_dir: 'results/analyses/maps/raw'
        parameters:
            assembly: 'chains'
            bin_size: 10
            blocks: -200